# Generated by Django 2.0.2 on 2018-03-05 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuildingManagerCore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='BuildingManagerCore.Building'),
        ),
        migrations.AddField(
            model_name='person',
            name='apartment',
            field=models.ManyToManyField(to='BuildingManagerCore.Apartment'),
        ),
    ]
